sudo: required

language: php
php:
  - 7.3.9

services:
  - docker

addons:
  chrome: stable

branches:
  only:
    - master

before_install:
  - nvm install 12.10.0
  - node -v
  - npm -v

before_script:
  - docker-compose up -d --build
  - docker ps -a
  - while [[ "$(curl -o /dev/null -Isw '%{http_code}\n' http://localhost/api/ping)" -ne 200 ]]; do sleep 3; echo "Waiting API to be available..."; done
  - docker logs backend
  - cd backend
  - composer install
  - cd ..
  - cd app
  - npm install
  - cd ..

script:
  - cd backend
  - composer run sniff
  - MYSQL_PORT=3308 && MYSQL_HOST=127.0.0.1
  - composer run test:unit
  - composer run test:functional
  - cd ..
  - cd app
  - npm run lint
  - npm run test
  - cd ..

after_script:
  - docker-compose down -v

notifications:
  email: false