  
dist: bionic
os:
  - linux
services:
  - docker
  - xvfb
language: node_js
node_js:
  - "12.16.1"
addons:
  apt:
    packages:
      - dpkg
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @angular/cli
  - cd app
install:
  - npm ci
script:
  - ng test --watch=false
  # - ng e2e
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never